# Output directory (relative).
out-dir = "../ryegen_bindings"
# Go name of package.
package = "gioui.org"
# Go semantic version of package.
version = "v0.7.1"
# Auto-remove "New" part of functions (e.g. widget.NewLabel => widget-label, app.New => app).
cut-new = true

# Add a build flag to exclude the binding (optional).
dont-build-flag = "b_no_gioui"

## Descending priority. Packages not listed will always be prefixed.
## In case of conflicting function names, only the function from the
## package with the highest priority is not prefixed.
#no-prefix = [
#  "github.com/<user>/<repo>",
#  "github.com/<user>/<repo>/important",
#]

## Set custom prefix for all symbols in the package (if applicable: see "no-prefix").
#custom-prefixes = [
#  ["my-fyne", "fyne.io/fyne/v2"],
#  ["my-widget", "fyne.io/fyne/v2/widget"],
#]

## Generate bindings for selected parts of the go standard library.
#include-std-libs = [
#  "image",
#]